services:
  # maker-bundle
  maker.maker.make_hsl_dto:
    class: Fd\HslBundle\Maker\MakeHslDto
    arguments: ["@maker.doctrine_helper"]
    tags: ["maker.command"]
  maker.maker.make_hsl_transformer:
    class: Fd\HslBundle\Maker\MakeHslTransformer
    arguments: ["@maker.doctrine_helper"]
    tags: ["maker.command"]
  maker.maker.make_hsl_crud:
    class: Fd\HslBundle\Maker\MakeHslCrud
    arguments: ["@maker.doctrine_helper"]
    tags: ["maker.command"]

  # Dto services
  Fd\HslBundle\DtoRequestResolver: # deprecated, will remove in next version.
    arguments: ["@validator"]
    tags:
      - { name: "controller.argument_value_resolver", priority: 50 }

  Fd\HslBundle\Dto\DtoRequestResolver:
    arguments: ["@validator"]
    tags:
      - { name: "controller.argument_value_resolver", priority: 50 }

  # paginator
  fdhsl.pagination.paginator:
    class: Fd\HslBundle\Pagination\Paginator

  Fd\HslBundle\Pagination\PaginatorInterface: "@fdhsl.pagination.paginator"

  # JsonResponseException
  Fd\HslBundle\Event\Listener\JsonResponseExceptionListener: # deprecated, will remove in next version.
    tags:
      - { name: kernel.event_listener, event: kernel.exception }

  # DtoValidationException
  Fd\HslBundle\Event\Listener\DtoValidationExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception }
