services:
  # maker-bundle
  maker.maker.make_hsl_dto:
    class: Fd\HslBundle\Maker\MakeHslDto
    arguments: ["@maker.doctrine_helper"]
    tags: ["maker.command"]
  maker.maker.make_hsl_transformer:
    class: Fd\HslBundle\Maker\MakeHslTransformer
    arguments: ["@maker.doctrine_helper"]
    tags: ["maker.command"]
  maker.maker.make_hsl_crud:
    class: Fd\HslBundle\Maker\MakeHslCrud
    arguments: ["@maker.doctrine_helper"]
    tags: ["maker.command"]

  # Dto services
  Fd\HslBundle\Dto\DtoRequestResolver:
    arguments: ["@validator"]
    tags:
      - { name: "controller.argument_value_resolver", priority: 50 }

  fdhsl.dto.validator.dto_validator:
    class: Fd\HslBundle\Dto\Validator\DtoValidator
    arguments: ["@validator"]
  Fd\HslBundle\Dto\Validator\DtoValidator:
    arguments: ["@validator"]
  Fd\HslBundle\Dto\Validator\DtoValidatorInterface: "@fdhsl.dto.validator.dto_validator"

  # paginator
  fdhsl.pagination.paginator:
    class: Fd\HslBundle\Pagination\Paginator
    arguments: ["@router", "@request_stack"]
  Fd\HslBundle\Pagination\Paginator:
    arguments: ["@router", "@request_stack"]
  Fd\HslBundle\Pagination\PaginatorInterface: "@fdhsl.pagination.paginator"

  # DtoValidationException
  fdhsl.event.dto_validation_exception_listener:
    class: Fd\HslBundle\Event\DtoValidationExceptionListener
    tags:
      - { name: kernel.event_listener, event: kernel.exception }
