services:
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # maker-bundle
  maker.maker.make_hsl_dto:
    class: Fd\HslBundle\Maker\MakeHslDto
    arguments: ["@maker.doctrine_helper"]
    #tags: ["maker.command"]
  maker.maker.make_hsl_transformer:
    class: Fd\HslBundle\Maker\MakeHslTransformer
    arguments: ["@maker.doctrine_helper"]
  maker.maker.make_hsl_crud:
    class: Fd\HslBundle\Maker\MakeHslCrud
    arguments: ["@maker.doctrine_helper"]

  Fd\HslBundle\Command\LexikJWTKeyGeneratorCommand:
    tags: ["console.command"]

  # transformers should be public because FractalBundle will fetch
  # services from container using service id.
  # App\Transformer\:
  #   resource: "%kernel.project_dir%/src/Transformer"
  #   public: true

  # Dto services
  Fd\HslBundle\DtoRequestResolver:
    #arguments: ["@validator"]
    tags:
      - { name: "controller.argument_value_resolver", priority: 50 }

  # Vich Uploader event
  Fd\HslBundle\Event\Listener\HslImageUploadListener:
    tags:
      - { name: kernel.event_listener, event: vich_uploader.post_upload }

  # paginator
  fdhsl.pagination.paginator:
    class: Fd\HslBundle\Pagination\Paginator

  Fd\HslBundle\Pagination\PaginatorInterface: "@fdhsl.pagination.paginator"

  # JsonResponseException
  Fd\HslBundle\Event\Listener\JsonResponseExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception }
